apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::156897219603:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-127MJA3AI4D4T
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::156897219603:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-06T09:33:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1706"
  uid: 8cf857aa-df28-440d-82b1-6f4bc95f3abb
